import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d  

# generated by Gemini
def plot_overlaid_lines(cortical_parcellation, anomalies=None, sigma=1.5):
    """
    Plots all networks overlaid on a single graph.
    Smoothed with a 1D Gaussian filter, using deviations from group standard deviation.
    """
    plt.style.use('dark_background')
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['grid.color'] = '#2A2A2A'
    
    first_net = list(cortical_parcellation.keys())[0]
    time_axis = np.arange(len(cortical_parcellation[first_net][0]))
    
    fig, ax = plt.subplots(figsize=(12, 6), facecolor='#121212')
    ax.set_facecolor('#121212')
    
    colors = ['#FF5A5F', '#FFB400', '#007A87', '#8CE070', '#7B0099', '#3B5998', '#00CAA6']
    
    for (network_name, (means_list, std_val)), color in zip(cortical_parcellation.items(), colors):
        means_array = np.array(means_list)
        denom_std = std_val if std_val != 0 else 1.0
        deviations = means_array / denom_std
        smoothed_deviations = gaussian_filter1d(deviations, sigma=sigma)
        
        ax.plot(time_axis, smoothed_deviations, label=network_name, color=color, linewidth=2, alpha=0.85)
        
    ax.axhline(y=0, color='#444444', linestyle=':', linewidth=1)
        
    if anomalies:
        for t_real in anomalies:
            ax.axvline(x=t_real, color='#FF3366', linestyle='--', linewidth=1.5, alpha=0.8)
            ax.text(t_real + 0.1, ax.get_ylim()[1] * 0.8, 
                    f"Anomaly\n{t_real}s", color='#FF3366', fontsize=9, weight='bold',
                    bbox=dict(facecolor='#121212', alpha=0.8, edgecolor='none'))

    ax.set_title("Network Group Deviations from STD (Overlaid Line Plot)", fontsize=14, pad=15, color='#E0E0E0', weight='bold')
    ax.set_xlabel("Real Time / Video Position (Seconds)", fontsize=11, color='#A0A0A0')
    ax.set_ylabel("Deviation Scale (Activation / Group STD)", fontsize=11, color='#A0A0A0')
    
    for spine in ['top', 'right', 'left', 'bottom']:
        ax.spines[spine].set_color('#2A2A2A')
        
    ax.grid(True, linestyle=':', alpha=0.5)
    ax.legend(loc='upper left', frameon=True, facecolor='#1E1E1E', edgecolor='#2A2A2A')
    
    plt.tight_layout()
    plt.show()