import numpy as np
import matplotlib.pyplot as plt

# generated by Gemini
def plot_time_surface_heatmap(cortical_parcellation, anomalies=None):
    """
    Plots all networks stacked into an image strip layout across time.
    Best for spotting solid vertical columns of joint activation shifts instantly.
    """
    plt.style.use('dark_background')
    network_names = list(cortical_parcellation.keys())
    time_series_matrix = np.array([cortical_parcellation[net][0] for net in network_names])
    
    fig, ax = plt.subplots(figsize=(14, 5), facecolor='#121212')
    cax = ax.imshow(time_series_matrix, aspect='auto', cmap='magma', interpolation='nearest')
    
    ax.set_title("Network Activation Carpet Plot Heatmap", fontsize=14, pad=15, color='#E0E0E0', weight='bold')
    ax.set_yticks(np.arange(len(network_names)))
    ax.set_yticklabels(network_names, color='#A0A0A0')
    ax.set_xlabel("Real Time / Video Position (Seconds)", fontsize=11, color='#A0A0A0')
    
    if anomalies:
        for t_real in anomalies:
            ax.axvline(x=t_real, color='#FF3366', linestyle='--', linewidth=2, alpha=0.9)
            
    fig.colorbar(cax, orientation='vertical', label='Z-Score Units', pad=0.02)
    plt.tight_layout()
    plt.show()