import numpy as np
import matplotlib.pyplot as plt

# generated by Gemini
def plot_network_correlation_matrix(cortical_parcellation):
    """
    Plots a stationary 7x7 matrix showing total linear correlation ($r$) between networks.
    Best for checking baseline functional connectivity partnerships.
    """
    plt.style.use('dark_background')
    network_names = list(cortical_parcellation.keys())
    matrix_data = np.array([cortical_parcellation[net][0] for net in network_names])
    
    corr_matrix = np.corrcoef(matrix_data)
    
    fig, ax = plt.subplots(figsize=(8, 7), facecolor='#121212')
    cax = ax.imshow(corr_matrix, cmap='RdBu_r', vmin=-1, vmax=1)
    
    ax.set_title("Inter-Network Correlation Matrix", fontsize=14, pad=15, color='#E0E0E0', weight='bold')
    ax.set_xticks(np.arange(len(network_names)))
    ax.set_yticks(np.arange(len(network_names)))
    ax.set_xticklabels(network_names, rotation=45, ha="right", color='#A0A0A0')
    ax.set_yticklabels(network_names, color='#A0A0A0')
    
    cbar = fig.colorbar(cax, fraction=0.046, pad=0.04)
    cbar.ax.tick_params(labelsize=10)
    cbar.set_label("Pearson Correlation Coefficient ($r$)", color='#A0A0A0', labelpad=10)
    
    plt.tight_layout()
    plt.show()