import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d  

# generated by Gemini
def plot_stacked_subplots(cortical_parcellation, anomalies=None, sigma=1.5):
    """
    Plots each network on its own separate subplot within a single shared figure.
    Best for scanning column-wise down a clean timeline to inspect precise correlations.
    """
    plt.style.use('dark_background')
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['grid.color'] = '#1F1F1F'
    
    network_names = list(cortical_parcellation.keys())
    n_networks = len(network_names)
    time_axis = np.arange(len(cortical_parcellation[network_names[0]][0]))
    
    fig, axes = plt.subplots(n_networks, 1, figsize=(14, 10), sharex=True, facecolor='#121212')
    colors = ['#FF5A5F', '#FFB400', '#007A87', '#8CE070', '#7B0099', '#3B5998', '#00CAA6']
    
    fig.suptitle("Cortical Network Deviations (Subplot Stack for Correlation Analysis)", 
                 fontsize=15, color='#E0E0E0', weight='bold', y=0.96)
    
    for i, (network_name, color) in enumerate(zip(network_names, colors)):
        ax = axes[i]
        ax.set_facecolor('#121212')
        
        means_list, std_val = cortical_parcellation[network_name]
        denom_std = std_val if std_val != 0 else 1.0
        deviations = np.array(means_list) / denom_std
        smoothed_deviations = gaussian_filter1d(deviations, sigma=sigma)
        
        ax.plot(time_axis, smoothed_deviations, color=color, linewidth=2, alpha=0.9)
        ax.axhline(y=0, color='#333333', linestyle=':', linewidth=1)
        
        ax.set_ylabel(network_name, rotation=0, fontsize=10, weight='bold', 
                      color='#A0A0A0', labelpad=20, ha='right', va='center')
        
        ax.tick_params(axis='y', labelsize=8, colors='#666666')
        for spine in ['top', 'right', 'bottom']:
            ax.spines[spine].set_visible(False)
        ax.spines['left'].set_color('#2A2A2A')
        ax.grid(True, linestyle=':', alpha=0.3)
        
        if anomalies:
            for t_real in anomalies:
                ax.axvline(x=t_real, color='#FF3366', linestyle='--', linewidth=1.5, alpha=0.7)
                if i == 0: 
                    ax.text(t_real + 0.1, ax.get_ylim()[1] * 0.7, "Anomaly", 
                            color='#FF3366', fontsize=8, weight='bold')

    axes[-1].spines['bottom'].set_visible(True)
    axes[-1].spines['bottom'].set_color('#2A2A2A')
    axes[-1].tick_params(axis='x', labelsize=10, colors='#A0A0A0')
    axes[-1].set_xlabel("Real Time / Video Position (Seconds)", fontsize=11, color='#A0A0A0', labelpad=10)
    
    plt.subplots_adjust(hspace=0.25, top=0.91, bottom=0.08, left=0.15, right=0.96)
    plt.show()
